# Generated by Django 4.0.5 on 2022-07-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
