# Generated by Django 4.0.5 on 2022-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_delete_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='nombre',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='edad',
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
