# Generated by Django 4.0.5 on 2022-08-22 21:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0005_rename_nombre_blog_autor_remove_blog_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
