# Generated by Django 4.0.5 on 2022-08-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_alter_blog_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=30),
        ),
    ]
